"""create import_job, record, quality_report tables

Revision ID: c70a413199ae
Revises: 
Create Date: 2026-07-28 18:55:07.026013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c70a413199ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('csv', 'pdf', 'excel', 'json', 'api', name='sourcetype'), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'finished', 'failed', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('quality_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_records', sa.Integer(), nullable=False),
    sa.Column('rejected_records', sa.Integer(), nullable=False),
    sa.Column('values_corrected', sa.Integer(), nullable=False),
    sa.Column('duplicates_removed', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_job_id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('accepted', 'rejected', name='recordstatus'), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('quality_report')
    op.drop_table('import_job')
    # ### end Alembic commands ###
